package org.sehkah.ddon.tools.extractor.lib.logic;

import org.sehkah.ddon.tools.extractor.lib.common.entity.TopLevelClientResource;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.ClientResourceDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.EncryptedArchiveDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.FileHeader;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.base.AbilityListDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.base.ItemListDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.base.LandInfoDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.clankyoten.FurnitureDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.game_common.PlayerExpTableDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.gui_cmn.WarpLocationDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.npc.SituationMsgCtrlDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.skill.CustomSkillDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.tutorial_guide.TutorialListDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.ui.uGUIAreaMaster.AreaMasterSpotDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season2.ui.uGUIAreaMaster.AreaMasterSpotDetailDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.EM.EmDmgTimerTblDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.EM.EmLvUpParamDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.EM.RageTableDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.MyRoom.AnimalDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.base.*;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.clankyoten.FurnitureGroupDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.clankyoten.FurnitureItemDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.clankyoten.FurnitureLayoutDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.clankyoten.MsgSetDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.craft_common.*;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.em_common.EmBaseInfoSvDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.em_common.EmDamageDirInfoDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.em_common.EvaluationTableDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.equip.EquipPresetDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.fieldarea.FieldAreaAdjoinListDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.fieldarea.FieldAreaMarkerInfoDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.game_common.*;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.gui_cmn.*;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.job.StaminaDecTblDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.npc_common.NpcConstItemDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.npc_common.NpcMeetingPlaceDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.quest.PawnQuestTalkDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.quest.QuestMarkerInfoDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.quest.QuestTextDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.scr.MapSpotDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.sg300000.ShopGoodsDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.skill.NormalSkillDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.stage.LocationDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.stage.Tbl2ChatMacroDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.tutorial_guide.TutorialDialogMessageDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.ui.history.QuestHistoryDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.ui.uGUIAreaMaster.AreaMasterRankDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.ui.uGUIArisenCard.AchievementHeaderDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.ui.uGUIDogmaOrb.GUIDogmaOrbDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.ui.uGUIKeyConfig.KeyConfigTextTableDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.deserialization.season3.ui.uGUISkill.AbilityAddDataDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.serialization.ClientResourceSerializer;
import org.sehkah.ddon.tools.extractor.lib.logic.serialization.SerializationFormat;
import org.sehkah.ddon.tools.extractor.lib.logic.serialization.season3.game_common.EnemyGroupSerializer;
import org.sehkah.ddon.tools.extractor.lib.logic.serialization.season3.game_common.GUIMessageSerializer;

import java.util.Map;

import static org.sehkah.ddon.tools.extractor.lib.logic.ClientResourceFileExtension.*;

public class ClientSeasonTwo extends ClientSeason {

    protected ClientSeasonTwo(SerializationFormat preferredSerializationType, boolean shouldSerializeMetaInformation) {
        super(preferredSerializationType, shouldSerializeMetaInformation);
    }

    @Override
    protected void setupClientResourceFiles(Map<ClientResourceFileExtension, ClientResourceFile> clientResourceFileMap) {
        clientResourceFileMap.put(rArchive, new ClientResourceFile(rArchive, new FileHeader("ARCC", 7, 2)));
        clientResourceFileMap.put(rAIPawnAutoWordTbl, new ClientResourceFile(rAIPawnAutoWordTbl, new FileHeader(4, 4)));
        clientResourceFileMap.put(rAbilityAddData, new ClientResourceFile(rAbilityAddData, new FileHeader(1, 4)));
        clientResourceFileMap.put(rAbilityData, new ClientResourceFile(rAbilityData, new FileHeader(3, 4)));
        clientResourceFileMap.put(rAbilityList, new ClientResourceFile(rAbilityList, new FileHeader("abl0", 8, 4)));
        clientResourceFileMap.put(rAchievement, new ClientResourceFile(rAchievement, new FileHeader(2, 4)));
        clientResourceFileMap.put(rAchievementHeader, new ClientResourceFile(rAchievementHeader, new FileHeader(3, 4)));
        clientResourceFileMap.put(rAdjustParam, new ClientResourceFile(rAdjustParam, new FileHeader(256, 4)));
        clientResourceFileMap.put(rAnimalData, new ClientResourceFile(rAnimalData, new FileHeader(0, 4)));
        clientResourceFileMap.put(rAreaInfo, new ClientResourceFile(rAreaInfo, new FileHeader("ARI\0", 2, 4)));
        clientResourceFileMap.put(rAreaInfoJointArea, new ClientResourceFile(rAreaInfoJointArea, new FileHeader("ARJ\0", 2, 4)));
        clientResourceFileMap.put(rAreaInfoStage, new ClientResourceFile(rAreaInfoStage, new FileHeader("ARS\0", 2, 4)));
        clientResourceFileMap.put(rAreaMasterRankData, new ClientResourceFile(rAreaMasterRankData, new FileHeader(4, 4)));
        clientResourceFileMap.put(rAreaMasterSpotData, new ClientResourceFile(rAreaMasterSpotData, new FileHeader(7, 4)));
        clientResourceFileMap.put(rAreaMasterSpotDetailData, new ClientResourceFile(rAreaMasterSpotDetailData, new FileHeader(4, 4)));
        clientResourceFileMap.put(rCraftCapPass, new ClientResourceFile(rCraftCapPass, new FileHeader(2, 4)));
        clientResourceFileMap.put(rCraftElementExp, new ClientResourceFile(rCraftElementExp, new FileHeader(1, 4)));
        clientResourceFileMap.put(rCraftQuality, new ClientResourceFile(rCraftQuality, new FileHeader(1, 4)));
        clientResourceFileMap.put(rCraftSkillCost, new ClientResourceFile(rCraftSkillCost, new FileHeader(2, 4)));
        clientResourceFileMap.put(rCraftSkillSpd, new ClientResourceFile(rCraftSkillSpd, new FileHeader(3, 4)));
        clientResourceFileMap.put(rCraftUpGradeExp, new ClientResourceFile(rCraftUpGradeExp, new FileHeader(1, 4)));
        clientResourceFileMap.put(rCustomSkillData, new ClientResourceFile(rCustomSkillData, new FileHeader(1, 4)));
        clientResourceFileMap.put(rCycleQuestInfo, new ClientResourceFile(rCycleQuestInfo, new FileHeader("CQI\0", 2, 4)));
        clientResourceFileMap.put(rEmBaseInfoSv, new ClientResourceFile(rEmBaseInfoSv, new FileHeader(8, 4)));
        clientResourceFileMap.put(rEmDamageDirInfo, new ClientResourceFile(rEmDamageDirInfo, new FileHeader(2, 4)));
        clientResourceFileMap.put(rEmDmgTimerTbl, new ClientResourceFile(rEmDmgTimerTbl, new FileHeader(2, 4)));
        clientResourceFileMap.put(rEmLvUpParam, new ClientResourceFile(rEmLvUpParam, new FileHeader(7, 4)));
        clientResourceFileMap.put(rEnemyGroup, new ClientResourceFile(rEnemyGroup, new FileHeader(1, 4)));
        clientResourceFileMap.put(rEquipPreset, new ClientResourceFile(rEquipPreset, new FileHeader(7, 4)));
        clientResourceFileMap.put(rEvaluationTable, new ClientResourceFile(rEvaluationTable, new FileHeader(4, 4)));
        clientResourceFileMap.put(rEventParam, new ClientResourceFile(rEventParam, new FileHeader(18, 4)));
        clientResourceFileMap.put(rFieldAreaAdjoinList, new ClientResourceFile(rFieldAreaAdjoinList, new FileHeader("FAA\0", 2, 4)));
        clientResourceFileMap.put(rFieldAreaList, new ClientResourceFile(rFieldAreaList, new FileHeader("FAl\0", 2, 4)));
        clientResourceFileMap.put(rFieldAreaMarkerInfo, new ClientResourceFile(rFieldAreaMarkerInfo, new FileHeader("FMI\0", 1, 4)));
        clientResourceFileMap.put(rFieldMapData, new ClientResourceFile(rFieldMapData, new FileHeader("fmd\0", 18, 4)));
        clientResourceFileMap.put(rFurnitureData, new ClientResourceFile(rFurnitureData, new FileHeader(4, 4)));
        clientResourceFileMap.put(rFurnitureGroup, new ClientResourceFile(rFurnitureGroup, new FileHeader(1, 4)));
        clientResourceFileMap.put(rFurnitureItem, new ClientResourceFile(rFurnitureItem, new FileHeader(1, 4)));
        clientResourceFileMap.put(rFurnitureLayout, new ClientResourceFile(rFurnitureLayout, new FileHeader(1, 4)));
        clientResourceFileMap.put(rGUIDogmaOrb, new ClientResourceFile(rGUIDogmaOrb, new FileHeader(1, 4)));
        clientResourceFileMap.put(rGUIMessage, new ClientResourceFile(rGUIMessage, new FileHeader("GMD\0", 66306, 4)));
        clientResourceFileMap.put(rGatheringItem, new ClientResourceFile(rGatheringItem, new FileHeader(1, 4)));
        clientResourceFileMap.put(rHumanEnemyCustomSkill, new ClientResourceFile(rHumanEnemyCustomSkill, new FileHeader(3, 4)));
        clientResourceFileMap.put(rHumanEnemyEquip, new ClientResourceFile(rHumanEnemyEquip, new FileHeader(3, 4)));
        clientResourceFileMap.put(rJobBaseParam, new ClientResourceFile(rJobBaseParam, new FileHeader(263, 4)));
        clientResourceFileMap.put(rJobLevelUpTbl2, new ClientResourceFile(rJobLevelUpTbl2, new FileHeader(1, 4)));
        clientResourceFileMap.put(rJobMasterCtrl, new ClientResourceFile(rJobMasterCtrl, new FileHeader(256, 4)));
        clientResourceFileMap.put(rJobTutorialQuestList, new ClientResourceFile(rJobTutorialQuestList, new FileHeader("JTQ\0", 1, 2)));
        clientResourceFileMap.put(rKeyConfigTextTable, new ClientResourceFile(rKeyConfigTextTable, new FileHeader(1, 4)));
        clientResourceFileMap.put(rLandInfo, new ClientResourceFile(rLandInfo, new FileHeader("LAI\0", 2, 4)));
        clientResourceFileMap.put(rLayoutPreset, new ClientResourceFile(rLayoutPreset, new FileHeader(5, 4)));
        clientResourceFileMap.put(rLocationData, new ClientResourceFile(rLocationData, new FileHeader("lcd\0", 16, 4)));
        clientResourceFileMap.put(rMapSpotData, new ClientResourceFile(rMapSpotData, new FileHeader("msd\0", 0, 4)));
        clientResourceFileMap.put(rMapSpotStageList, new ClientResourceFile(rMapSpotStageList, new FileHeader("msl\0", 0, 4)));
        clientResourceFileMap.put(rMsgSet, new ClientResourceFile(rMsgSet, new FileHeader("mgst", 3, 2)));
        clientResourceFileMap.put(rNamedParam, new ClientResourceFile(rNamedParam, new FileHeader(5, 4)));
        clientResourceFileMap.put(rNormalSkillData, new ClientResourceFile(rNormalSkillData, new FileHeader(5, 4)));
        clientResourceFileMap.put(rNpcConstItem, new ClientResourceFile(rNpcConstItem, new FileHeader(2, 4)));
        clientResourceFileMap.put(rNpcMeetingPlace, new ClientResourceFile(rNpcMeetingPlace, new FileHeader(0, 4)));
        clientResourceFileMap.put(rPawnQuestTalk, new ClientResourceFile(rPawnQuestTalk, new FileHeader("PQT\0", 1, 4)));
        clientResourceFileMap.put(rPlPartsInfo, new ClientResourceFile(rPlPartsInfo, new FileHeader("PSI\0", 1, 4)));
        clientResourceFileMap.put(rPrologueHmStatus, new ClientResourceFile(rPrologueHmStatus, new FileHeader(0, 4)));
        clientResourceFileMap.put(rQuestHistoryData, new ClientResourceFile(rQuestHistoryData, new FileHeader(1, 4)));
        clientResourceFileMap.put(rQuestMarkerInfo, new ClientResourceFile(rQuestMarkerInfo, new FileHeader("QMI\0", 1, 4)));
        clientResourceFileMap.put(rQuestSequenceList, new ClientResourceFile(rQuestSequenceList, new FileHeader(256, 4)));
        clientResourceFileMap.put(rQuestTextData, new ClientResourceFile(rQuestTextData, new FileHeader("QTD\0", 2, 4)));
        clientResourceFileMap.put(rRageTable, new ClientResourceFile(rRageTable, new FileHeader(257, 4)));
        clientResourceFileMap.put(rShopGoods, new ClientResourceFile(rShopGoods, new FileHeader("TBL\0", 259, 4)));
        clientResourceFileMap.put(rShrinkBlowValue, new ClientResourceFile(rShrinkBlowValue, new FileHeader(2, 4)));
        clientResourceFileMap.put(rSituationMsgCtrl, new ClientResourceFile(rSituationMsgCtrl, new FileHeader("SMC\0", 2, 4)));
        clientResourceFileMap.put(rStageAdjoinList, new ClientResourceFile(rStageAdjoinList, new FileHeader("SAL\0", 4, 4)));
        clientResourceFileMap.put(rStageList, new ClientResourceFile(rStageList, new FileHeader("slt\0", 34, 4)));
        clientResourceFileMap.put(rStageMap, new ClientResourceFile(rStageMap, new FileHeader(1, 4)));
        clientResourceFileMap.put(rStageToSpot, new ClientResourceFile(rStageToSpot, new FileHeader(0, 4)));
        clientResourceFileMap.put(rStaminaDecTbl, new ClientResourceFile(rStaminaDecTbl, new FileHeader("sdt\0", 5, 4)));
        clientResourceFileMap.put(rStartPosArea, new ClientResourceFile(rStartPosArea, new FileHeader(0, 4)));
        clientResourceFileMap.put(rStatusGainTable, new ClientResourceFile(rStatusGainTable, new FileHeader(257, 4)));
        clientResourceFileMap.put(rTbl2ChatMacro, new ClientResourceFile(rTbl2ChatMacro, new FileHeader(256, 4)));
        clientResourceFileMap.put(rTutorialDialogMessage, new ClientResourceFile(rTutorialDialogMessage, new FileHeader("TDM\0", 2, 4)));
        clientResourceFileMap.put(rTutorialList, new ClientResourceFile(rTutorialList, new FileHeader("TLT\0", 5, 4)));
        clientResourceFileMap.put(rTutorialQuestGroup, new ClientResourceFile(rTutorialQuestGroup, new FileHeader("TQG\0", 1, 2)));
        clientResourceFileMap.put(rWarpLocation, new ClientResourceFile(rWarpLocation, new FileHeader(352, 4)));
        clientResourceFileMap.put(rPlayerExpTable, new ClientResourceFile(rPlayerExpTable, new FileHeader(2, 4)));
        clientResourceFileMap.put(rItemList, new ClientResourceFile(rItemList, new FileHeader("ipa\0", 58, 4)));
    }

    @Override
    protected void setupDeserializers(Map<ClientResourceFileExtension, ClientResourceDeserializer<TopLevelClientResource>> deserializerMap) {
        deserializerMap.put(rArchive, new EncryptedArchiveDeserializer(clientResourceFileMap.get(rArchive)));
        deserializerMap.put(rAIPawnAutoWordTbl, new AIPawnAutoWordTblDeserializer(clientResourceFileMap.get(rAIPawnAutoWordTbl)));
        deserializerMap.put(rAbilityAddData, new AbilityAddDataDeserializer(clientResourceFileMap.get(rAbilityAddData)));
        deserializerMap.put(rAbilityData, new AbilityDataDeserializer(clientResourceFileMap.get(rAbilityData)));
        deserializerMap.put(rAbilityList, new AbilityListDeserializer(clientResourceFileMap.get(rAbilityList)));
        deserializerMap.put(rAchievement, new AchievementDeserializer(clientResourceFileMap.get(rAchievement)));
        deserializerMap.put(rAchievementHeader, new AchievementHeaderDeserializer(clientResourceFileMap.get(rAchievementHeader)));
        deserializerMap.put(rAdjustParam, new JobAdjustParamDeserializer(clientResourceFileMap.get(rAdjustParam)));
        deserializerMap.put(rAnimalData, new AnimalDataDeserializer(clientResourceFileMap.get(rAnimalData)));
        deserializerMap.put(rAreaInfo, new AreaInfoDeserializer(clientResourceFileMap.get(rAreaInfo)));
        deserializerMap.put(rAreaInfoJointArea, new AreaInfoJointAreaDeserializer(clientResourceFileMap.get(rAreaInfoJointArea)));
        deserializerMap.put(rAreaInfoStage, new AreaInfoStageDeserializer(clientResourceFileMap.get(rAreaInfoStage)));
        deserializerMap.put(rAreaMasterRankData, new AreaMasterRankDataDeserializer(clientResourceFileMap.get(rAreaMasterRankData)));
        deserializerMap.put(rAreaMasterSpotData, new AreaMasterSpotDataDeserializer(clientResourceFileMap.get(rAreaMasterSpotData)));
        deserializerMap.put(rAreaMasterSpotDetailData, new AreaMasterSpotDetailDataDeserializer(clientResourceFileMap.get(rAreaMasterSpotDetailData)));
        deserializerMap.put(rCraftCapPass, new CraftCapPassDeserializer(clientResourceFileMap.get(rCraftCapPass)));
        deserializerMap.put(rCraftElementExp, new CraftElementExpDeserializer(clientResourceFileMap.get(rCraftElementExp)));
        deserializerMap.put(rCraftQuality, new CraftQualityDeserializer(clientResourceFileMap.get(rCraftQuality)));
        deserializerMap.put(rCraftSkillCost, new CraftSkillCostDeserializer(clientResourceFileMap.get(rCraftSkillCost)));
        deserializerMap.put(rCraftSkillSpd, new CraftSkillSpeedDeserializer(clientResourceFileMap.get(rCraftSkillSpd)));
        deserializerMap.put(rCraftUpGradeExp, new CraftUpGradeExpDeserializer(clientResourceFileMap.get(rCraftUpGradeExp)));
        deserializerMap.put(rCustomSkillData, new CustomSkillDataDeserializer(clientResourceFileMap.get(rCustomSkillData)));
        deserializerMap.put(rCycleQuestInfo, new CycleQuestInfoDeserializer(clientResourceFileMap.get(rCycleQuestInfo)));
        deserializerMap.put(rEmBaseInfoSv, new EmBaseInfoSvDeserializer(clientResourceFileMap.get(rEmBaseInfoSv)));
        deserializerMap.put(rEmDamageDirInfo, new EmDamageDirInfoDeserializer(clientResourceFileMap.get(rEmDamageDirInfo)));
        deserializerMap.put(rEmDmgTimerTbl, new EmDmgTimerTblDeserializer(clientResourceFileMap.get(rEmDmgTimerTbl)));
        deserializerMap.put(rEmLvUpParam, new EmLvUpParamDeserializer(clientResourceFileMap.get(rEmLvUpParam)));
        deserializerMap.put(rEnemyGroup, new EnemyGroupDeserializer(clientResourceFileMap.get(rEnemyGroup)));
        deserializerMap.put(rEquipPreset, new EquipPresetDeserializer(clientResourceFileMap.get(rEquipPreset)));
        deserializerMap.put(rEvaluationTable, new EvaluationTableDeserializer(clientResourceFileMap.get(rEvaluationTable)));
        deserializerMap.put(rEventParam, new EventParamDeserializer(clientResourceFileMap.get(rEventParam)));
        deserializerMap.put(rFieldAreaAdjoinList, new FieldAreaAdjoinListDeserializer(clientResourceFileMap.get(rFieldAreaAdjoinList)));
        deserializerMap.put(rFieldAreaList, new FieldAreaListDeserializer(clientResourceFileMap.get(rFieldAreaList)));
        deserializerMap.put(rFieldAreaMarkerInfo, new FieldAreaMarkerInfoDeserializer(clientResourceFileMap.get(rFieldAreaMarkerInfo)));
        deserializerMap.put(rFieldMapData, new FieldMapDataDeserializer(clientResourceFileMap.get(rFieldMapData)));
        deserializerMap.put(rFurnitureData, new FurnitureDataDeserializer(clientResourceFileMap.get(rFurnitureData)));
        deserializerMap.put(rFurnitureGroup, new FurnitureGroupDeserializer(clientResourceFileMap.get(rFurnitureGroup)));
        deserializerMap.put(rFurnitureItem, new FurnitureItemDeserializer(clientResourceFileMap.get(rFurnitureItem)));
        deserializerMap.put(rFurnitureLayout, new FurnitureLayoutDeserializer(clientResourceFileMap.get(rFurnitureLayout)));
        deserializerMap.put(rGUIDogmaOrb, new GUIDogmaOrbDeserializer(clientResourceFileMap.get(rGUIDogmaOrb)));
        deserializerMap.put(rGUIMessage, new GUIMessageDeserializer(clientResourceFileMap.get(rGUIMessage)));
        deserializerMap.put(rGatheringItem, new GatheringItemDeserializer(clientResourceFileMap.get(rGatheringItem)));
        deserializerMap.put(rHumanEnemyCustomSkill, new HumanEnemyCustomSkillDeserializer(clientResourceFileMap.get(rHumanEnemyCustomSkill)));
        deserializerMap.put(rHumanEnemyEquip, new HumanEnemyEquipDeserializer(clientResourceFileMap.get(rHumanEnemyEquip)));
        deserializerMap.put(rJobBaseParam, new JobBaseParamDeserializer(clientResourceFileMap.get(rJobBaseParam)));
        deserializerMap.put(rJobLevelUpTbl2, new JobLevelUpTableDeserializer(clientResourceFileMap.get(rJobLevelUpTbl2)));
        deserializerMap.put(rJobMasterCtrl, new JobMasterCtrlDeserializer(clientResourceFileMap.get(rJobMasterCtrl)));
        deserializerMap.put(rJobTutorialQuestList, new JobTutorialQuestListDeserializer(clientResourceFileMap.get(rJobTutorialQuestList)));
        deserializerMap.put(rKeyConfigTextTable, new KeyConfigTextTableDeserializer(clientResourceFileMap.get(rKeyConfigTextTable)));
        deserializerMap.put(rLandInfo, new LandInfoDeserializer(clientResourceFileMap.get(rLandInfo)));
        deserializerMap.put(rLayoutPreset, new LayoutPresetDeserializer(clientResourceFileMap.get(rLayoutPreset)));
        deserializerMap.put(rLocationData, new LocationDataDeserializer(clientResourceFileMap.get(rLocationData)));
        deserializerMap.put(rMapSpotData, new MapSpotDataDeserializer(clientResourceFileMap.get(rMapSpotData)));
        deserializerMap.put(rMapSpotStageList, new MapSpotStageListDeserializer(clientResourceFileMap.get(rMapSpotStageList)));
        deserializerMap.put(rMsgSet, new MsgSetDeserializer(clientResourceFileMap.get(rMsgSet)));
        deserializerMap.put(rNamedParam, new NamedParamDeserializer(clientResourceFileMap.get(rNamedParam)));
        deserializerMap.put(rNormalSkillData, new NormalSkillDataDeserializer(clientResourceFileMap.get(rNormalSkillData)));
        deserializerMap.put(rNpcConstItem, new NpcConstItemDeserializer(clientResourceFileMap.get(rNpcConstItem)));
        deserializerMap.put(rNpcMeetingPlace, new NpcMeetingPlaceDeserializer(clientResourceFileMap.get(rNpcMeetingPlace)));
        deserializerMap.put(rPawnQuestTalk, new PawnQuestTalkDeserializer(clientResourceFileMap.get(rPawnQuestTalk)));
        deserializerMap.put(rPlPartsInfo, new PlPartsInfoDeserializer(clientResourceFileMap.get(rPlPartsInfo)));
        deserializerMap.put(rPrologueHmStatus, new PrologueHmStatusDeserializer(clientResourceFileMap.get(rPrologueHmStatus)));
        deserializerMap.put(rQuestHistoryData, new QuestHistoryDataDeserializer(clientResourceFileMap.get(rQuestHistoryData)));
        deserializerMap.put(rQuestMarkerInfo, new QuestMarkerInfoDeserializer(clientResourceFileMap.get(rQuestMarkerInfo)));
        deserializerMap.put(rQuestSequenceList, new QuestSequenceListDeserializer(clientResourceFileMap.get(rQuestSequenceList)));
        deserializerMap.put(rQuestTextData, new QuestTextDataDeserializer(clientResourceFileMap.get(rQuestTextData)));
        deserializerMap.put(rRageTable, new RageTableDeserializer(clientResourceFileMap.get(rRageTable)));
        deserializerMap.put(rShopGoods, new ShopGoodsDeserializer(clientResourceFileMap.get(rShopGoods)));
        deserializerMap.put(rShrinkBlowValue, new ShrinkBlowValueDeserializer(clientResourceFileMap.get(rShrinkBlowValue)));
        deserializerMap.put(rSituationMsgCtrl, new SituationMsgCtrlDeserializer(clientResourceFileMap.get(rSituationMsgCtrl)));
//        deserializerMap.put(rStageAdjoinList, new StageAdjoinListDeserializer(clientResourceFileMap.get(rStageAdjoinList))); // TODO: In season 2 SAL exists in both version 3 & 4 at the same time!
        deserializerMap.put(rStageList, new StageListDeserializer(clientResourceFileMap.get(rStageList)));
        deserializerMap.put(rStageMap, new StageMapDeserializer(clientResourceFileMap.get(rStageMap)));
        deserializerMap.put(rStageToSpot, new StageToSpotDeserializer(clientResourceFileMap.get(rStageToSpot)));
        deserializerMap.put(rStaminaDecTbl, new StaminaDecTblDeserializer(clientResourceFileMap.get(rStaminaDecTbl)));
        deserializerMap.put(rStartPosArea, new StartPosAreaDeserializer(clientResourceFileMap.get(rStartPosArea)));
        deserializerMap.put(rStatusGainTable, new StatusGainTableDeserializer(clientResourceFileMap.get(rStatusGainTable)));
        deserializerMap.put(rTbl2ChatMacro, new Tbl2ChatMacroDeserializer(clientResourceFileMap.get(rTbl2ChatMacro)));
        deserializerMap.put(rTutorialDialogMessage, new TutorialDialogMessageDeserializer(clientResourceFileMap.get(rTutorialDialogMessage)));
        deserializerMap.put(rTutorialList, new TutorialListDeserializer(clientResourceFileMap.get(rTutorialList)));
        deserializerMap.put(rTutorialQuestGroup, new TutorialQuestGroupDeserializer(clientResourceFileMap.get(rTutorialQuestGroup)));
        deserializerMap.put(rWarpLocation, new WarpLocationDeserializer(clientResourceFileMap.get(rWarpLocation)));
        deserializerMap.put(rPlayerExpTable, new PlayerExpTableDeserializer(clientResourceFileMap.get(rPlayerExpTable)));
        deserializerMap.put(rItemList, new ItemListDeserializer(clientResourceFileMap.get(rItemList)));
    }

    @Override
    protected void setupSerializers(Map<ClientResourceFileExtension, ClientResourceSerializer<? extends TopLevelClientResource>> serializerMap) {
        serializerMap.put(rEnemyGroup, new EnemyGroupSerializer(clientResourceFileMap.get(rEnemyGroup)));
        serializerMap.put(rGUIMessage, new GUIMessageSerializer(clientResourceFileMap.get(rGUIMessage)));
    }
}
