/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.sehkah.ddon.tools;

import org.sehkah.ddon.tools.extractor.Extractor;
import picocli.CommandLine;

public class Main {
    public static void main(String... args) {
        int exitCode = new CommandLine(new Extractor()).execute(args);
        System.exit(exitCode);
    }
}
