package org.sehkah.ddon.tools.extractor.season3.resource.entity.game_common.meta;

import java.util.Arrays;

public enum AIPawnActionGroupType {
    AIPAWN_ACT_GROUP_NONE(0x0),
    AIPAWN_ACT_GROUP_ATK_PHYS(0x1),
    AIPAWN_ACT_GROUP_ATK_MAGIC(0x2),
    AIPAWN_ACT_GROUP_ATK_SLASH(0x3),
    AIPAWN_ACT_GROUP_ATK_BLOW(0x4),
    AIPAWN_ACT_GROUP_ATK_SHOT(0x5),
    AIPAWN_ACT_GROUP_ATK_FIRE(0x6),
    AIPAWN_ACT_GROUP_ATK_ICE(0x7),
    AIPAWN_ACT_GROUP_ATK_THUNDER(0x8),
    AIPAWN_ACT_GROUP_ATK_HOLY(0x9),
    AIPAWN_ACT_GROUP_ATK_DARK(0xA),
    AIPAWN_ACT_GROUP_OCD_POISON(0xB),
    AIPAWN_ACT_GROUP_OCD_SLOW(0xC),
    AIPAWN_ACT_GROUP_OCD_SLEEP(0xD),
    AIPAWN_ACT_GROUP_OCD_FAINT(0xE),
    AIPAWN_ACT_GROUP_OCD_SEAL(0xF),
    AIPAWN_ACT_GROUP_OCD_SOFT_BODY(0x10),
    AIPAWN_ACT_GROUP_OCD_STONE(0x11),
    AIPAWN_ACT_GROUP_OCD_GOLD(0x12),
    AIPAWN_ACT_GROUP_OCD_SPREAD(0x13),
    AIPAWN_ACT_GROUP_OCD_FREEZE(0x14),
    AIPAWN_ACT_GROUP_OCD_ELECTRIC(0x15),
    AIPAWN_ACT_GROUP_OCD_HOLY_ABSORP(0x16),
    AIPAWN_ACT_GROUP_OCD_DARK_FOG(0x17),
    AIPAWN_ACT_GROUP_SP_NO_ATK(0x18),
    AIPAWN_ACT_GROUP_SP_KUZUSHI(0x19),
    AIPAWN_ACT_GROUP_SP_GUARD_BREAK(0x1A),
    AIPAWN_ACT_GROUP_SP_LAUNCH(0x1B),
    AIPAWN_ACT_GROUP_SP_CLUTCHED(0x1C),
    AIPAWN_ACT_GROUP_SP_HARD_HIT(0x1D),
    AIPAWN_ACT_GROUP_SP_COMBO(0x1E),
    AIPAWN_ACT_GROUP_SP_PIERCE(0x1F),
    AIPAWN_ACT_GROUP_SP_SUPPORT(0x20),
    AIPAWN_ACT_GROUP_SP_ATTACK(0x21),
    AIPAWN_ACT_GROUP_SP_EM_CLIMB_ACT(0x22),
    AIPAWN_ACT_GROUP_SP_ELM_CHANGE(0x23),
    AIPAWN_ACT_GROUP_SP_NO_ENCHANT(0x24),
    AIPAWN_ACT_GROUP_SP_EM_CLIMB(0x25),
    AIPAWN_ACT_GROUP_SP_HEAL(0x26),
    AIPAWN_ACT_GROUP_SP_CURE(0x27),
    AIPAWN_ACT_GROUP_SP_EVA(0x28),
    AIPAWN_ACT_GROUP_SP_POWER_UP(0x29),
    AIPAWN_ACT_GROUP_SP_POWER_DN(0x2A),
    AIPAWN_ACT_GROUP_SP_ENCHANT(0x2B),
    AIPAWN_ACT_GROUP_SP_BIND(0x2C),
    AIPAWN_ACT_GROUP_SP_ATK_ANIMAL(0x2D),
    AIPAWN_ACT_GROUP_SP_ARROW_CHG_ACT(0x2E),
    AIPAWN_ACT_GROUP_SP_YUSABURI(0x2F),
    AIPAWN_ACT_GROUP_SP_SEARCH_CORE(0x30),
    AIPAWN_ACT_GROUP_SP_MEDAL_CHG_ACT(0x31),
    AIPAWN_ACT_GROUP_SP_CATAPULT(0x32),
    AIPAWN_ACT_GROUP_SP_EM_CLIMB_ATK(0x33),
    AIPAWN_ACT_GROUP_SP_SEARCH_MASK(0x34),
    AIPAWN_ACT_GROUP_SP_POWER_UP_FOR_SELF(0x35),
    AIPAWN_ACT_GROUP_SP_HEAL_STAMINA(0x36),
    AIPAWN_ACT_GROUP_SP_SEARCH_CORE_ORDER(0x37),
    AIPAWN_ACT_GROUP_OCD_BAD_PHYS_ATK(0x38),
    AIPAWN_ACT_GROUP_OCD_BAD_PHYS_DEF(0x39),
    AIPAWN_ACT_GROUP_OCD_BAD_MGC_ATK(0x3A),
    AIPAWN_ACT_GROUP_OCD_BAD_MGC_DEF(0x3B),
    AIPAWN_ACT_GROUP_SP_NO_ELEMENT(0x3C);


    public final long value;

    AIPawnActionGroupType(long value) {
        this.value = value;
    }

    public static AIPawnActionGroupType of(long value) {
        return Arrays.stream(AIPawnActionGroupType.values()).filter(t -> t.value == value).findFirst().orElse(null);
    }
}
