package org.sehkah.ddon.tools.extractor.season1.logic.resource;

import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.sehkah.ddon.tools.extractor.lib.common.entity.FileHeader;
import org.sehkah.ddon.tools.extractor.lib.common.serialization.SerializationFormat;
import org.sehkah.ddon.tools.extractor.lib.logic.resource.ClientResourceFile;
import org.sehkah.ddon.tools.extractor.lib.logic.resource.ClientResourceFileManager;
import org.sehkah.ddon.tools.extractor.lib.logic.resource.deserialization.EncryptedArchiveDeserializer;
import org.sehkah.ddon.tools.extractor.lib.logic.resource.deserialization.ReferenceArchiveDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.base.ItemListDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.base.OmParamDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.game_common.PlayerExpTableDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.Human.BakeJointTblDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.Human.CatchInfoParamTblDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.Human.CaughtInfoParamTblDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.Human.WeaponOffsetTblDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.character_edit.EditStageParamDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.collision_common.PushRateListDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.effect_common.VfxLightInfluenceListDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.equip.EquipPresetDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.fieldarea.FieldAreaAdjoinListDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.fieldarea.FieldAreaMarkerInfoDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.launcher.ArchiveListArrayDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.marker.DungeonMarkerDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.marker.StageAdjoinList2Deserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.marker.StageAdjoinListDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.npc.SituationMsgCtrlDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.om.OmKeyDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.om.OmParamPartDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.pawn.AIPawnActNoSwitchTblDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.pawn.AISensorDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.quest.PawnQuestTalkDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.quest.QuestListDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.quest.QuestMarkerInfoDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.quest.QuestTextDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.scr.MapSpotDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.sg300000.ShopGoodsDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.skill.CustomSkillDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.skill.NormalSkillDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.tutorial_guide.TutorialDialogMessageDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.tutorial_guide.TutorialListDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.history.QuestHistoryDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.uGUIAreaMaster.AreaMasterRankDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.uGUIAreaMaster.AreaMasterSpotDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.uGUIAreaMaster.AreaMasterSpotDetailDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.uGUIArisenCard.AchievementHeaderDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.uGUIDogmaOrb.GUIDogmaOrbDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.uGUIKeyConfig.KeyConfigTextTableDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.ui.uGUISkill.AbilityAddDataDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.wep_res_table.WeaponResTableDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.wep_res_table.WepCateResTblDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season1.game_common.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.quest.AIFSMDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.stage.StageCustomPartsDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.EM.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.MyRoom.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.base.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.base.AreaInfoDeserializer;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.clankyoten.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.craft_common.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.em_common.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.game_common.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.gui_cmn.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.job.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.npc_common.*;
import org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season3.stage.*;

import java.nio.file.Path;
import java.util.Set;

import static org.sehkah.ddon.tools.extractor.lib.logic.resource.ClientResourceFileExtension.*;

@Slf4j
@Getter
public class ClientResourceFileManagerSeason1  extends ClientResourceFileManager {

    public ClientResourceFileManagerSeason1(Path clientRootFolder, SerializationFormat preferredSerializationType, boolean shouldSerializeMetaInformation) {
        super(preferredSerializationType, shouldSerializeMetaInformation);
        DynamicResourceLookupUtil.initialize(clientRootFolder);
    }

    @Override
    public void setup(Set<ClientResourceFile> clientResourceFileSet) {
        setupClientResourceFiles(clientResourceFileSet);
    }

    private static void setupClientResourceFiles(Set<ClientResourceFile> clientResourceFileSet) {
        clientResourceFileSet.add(new ClientResourceFile(rArchive, new FileHeader("ARCC", 7, 2), EncryptedArchiveDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rArchive, new FileHeader("ARCS", 7, 2), ReferenceArchiveDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rArchiveListArray, new FileHeader(11, 4), ArchiveListArrayDeserializer.class));


        clientResourceFileSet.add(new ClientResourceFile(rAbilityAddData, new FileHeader(1, 4), AbilityAddDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAbilityData, new FileHeader(3, 4), AbilityDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAbilityList, new FileHeader("abl0", 9, 4), AbilityListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAchievement, new FileHeader(2, 4), AchievementDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAchievementHeader, new FileHeader(3, 4), AchievementHeaderDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAdjLimitParam, new FileHeader(5, 4), AdjLimitParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAdjustParam, new FileHeader(256, 4), JobAdjustParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIPawnActNoSwitch, new FileHeader(5, 4), AIPawnActNoSwitchTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIPawnAutoMotionTbl, new FileHeader(6, 4), AIPawnAutoMotionTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIPawnAutoWordTbl, new FileHeader(4, 4), AIPawnAutoWordTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIPawnEmParam, new FileHeader(17, 4), AIPawnEmParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIPawnOrder, new FileHeader(15, 4), AIPawnOrderDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIPawnSkillParamTbl, new FileHeader(6, 4), AIPawnSkillParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAISensor, new FileHeader("SNR2", 1, 4), AISensorDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAnimalData, new FileHeader(0, 4), AnimalDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaInfo, new FileHeader("ARI\0", 2, 4), AreaInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaInfoJointArea, new FileHeader("ARJ\0", 2, 4), AreaInfoJointAreaDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaInfoStage, new FileHeader("ARS\0", 2, 4), AreaInfoStageDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaMasterRankData, new FileHeader(4, 4), AreaMasterRankDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaMasterSpotData, new FileHeader(8, 4), AreaMasterSpotDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaMasterSpotDetailData, new FileHeader(5, 4), AreaMasterSpotDetailDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rBakeJoint, new FileHeader(3, 4), BakeJointTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rBitTable, new FileHeader(2, 4), BitTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rBlowSaveEmLvParam, new FileHeader(2, 4), BlowSaveEmLvParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCalcDamageAtdmAdj, new FileHeader(1, 4), CalcDamageAtdmAdjTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCalcDamageAtdmAdjRate, new FileHeader(1, 4), CalcDamageAtdmAdjRateTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCalcDamageLvAdj, new FileHeader(17, 4), CalcDamageLvAdjTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCatchInfoParam, new FileHeader(19, 4), CatchInfoParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCaughtDamageRateRefTbl, new FileHeader(1, 4), CaughtDamageRateRefTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCaughtDamageRateTbl, new FileHeader(1, 4), CaughtDamageRateTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCaughtInfoParam, new FileHeader(16, 4), CaughtInfoParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCharParamEnemy, new FileHeader("cpe\0", 11, 4), CharParamEnemyTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftCapPass, new FileHeader(2, 4), CraftCapPassDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftElementExp, new FileHeader(1, 4), CraftElementExpDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftQuality, new FileHeader(1, 4), CraftQualityDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftSkillCost, new FileHeader(2, 4), CraftSkillCostDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftSkillSpd, new FileHeader(3, 4), CraftSkillSpeedDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftUpGradeExp, new FileHeader(1, 4), CraftUpGradeExpDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCustomSkillData, new FileHeader(3, 4), CustomSkillDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCycleQuestInfo, new FileHeader("CQI\0", 2, 4), CycleQuestInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCycleContentsSortieInfo, new FileHeader(1, 4), CycleContentsSortieInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEndContentsSortieInfo, new FileHeader(4, 4), EndContentsSortieInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPackageQuestInfo, new FileHeader("PQI\0", 2, 4), PackageQuestInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rDungeonMarker, new FileHeader("DMI\0", 1, 4), DungeonMarkerDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmBaseInfoSv, new FileHeader(21, 4), EmBaseInfoSvDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmDamageDirInfo, new FileHeader(2, 4), EmDamageDirInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmDmgTimerTbl, new FileHeader(2, 4), EmDmgTimerTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEditStageParam, new FileHeader("esp\0", 12, 4), EditStageParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmLvUpParam, new FileHeader(7, 4), EmLvUpParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmScaleTable, new FileHeader(257, 4), EmScaleTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPartsCtrlTable, new FileHeader(256, 4), PartsCtrlTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEnemyLocalEst, new FileHeader(259, 4), EnemyLocalEstTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEnemyMaterialTable, new FileHeader(260, 4), EnemyMaterialTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOcdElectricParam, new FileHeader(1, 4), OcdElectricParamListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmSoundTable, new FileHeader(261, 4), EmSoundTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEnemyStatusChange, new FileHeader(9, 4), EnemyStatusChangeTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmWorkRateTable, new FileHeader(258, 4), EmWorkRateTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJointOrder, new FileHeader(3, 4), JointOrderTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOcdImmuneParamRes, new FileHeader(37, 4), OcdImmuneParamResTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rParentRegionStatusParam, new FileHeader(65, 4), ParentRegionStatusParamTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rChildRegionStatusParamList, new FileHeader(65, 4), ChildRegionStatusParamListTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rChildRegionStatusParam, new FileHeader(65, 4), ChildRegionStatusParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEnemyReactResEx, new FileHeader(3, 4), EnemyReactResExTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEnemyReactResEx, new FileHeader(6, 4), EnemyReactResExTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmWarpParam, new FileHeader(3, 4), EmWarpParamTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJumpParamTbl, new FileHeader(4, 4), JumpParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJointInfo, new FileHeader(6, 4), JointInfoTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJointInfo, new FileHeader(259, 4), JointInfoTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEnemyGroup, new FileHeader(1, 4), EnemyGroupDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEquipPreset, new FileHeader(7, 4), EquipPresetDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEvaluationTable, new FileHeader(4, 4), EvaluationTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEventParam, new FileHeader(19, 4), EventParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFieldAreaAdjoinList, new FileHeader("FAA\0", 2, 4), FieldAreaAdjoinListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFieldAreaList, new FileHeader("FAl\0", 2, 4), FieldAreaListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFieldAreaMarkerInfo, new FileHeader("FMI\0", 1, 4), FieldAreaMarkerInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFieldMapData, new FileHeader("fmd\0", 18, 4), FieldMapDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFurnitureData, new FileHeader(5, 4), FurnitureDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFurnitureGroup, new FileHeader(1, 4), FurnitureGroupDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFurnitureItem, new FileHeader(1, 4), FurnitureItemDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFurnitureLayout, new FileHeader(1, 4), FurnitureLayoutDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rGatheringItem, new FileHeader(1, 4), GatheringItemDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rGUIDogmaOrb, new FileHeader(1, 4), GUIDogmaOrbDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rGUIMessage, new FileHeader("GMD\0", 66306, 4), GUIMessageDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rHumanEnemyCustomSkill, new FileHeader(3, 4), HumanEnemyCustomSkillDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rHumanEnemyEquip, new FileHeader(3, 4), HumanEnemyEquipDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJobBaseParam, new FileHeader(263, 4), JobBaseParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJobLevelUpTbl2, new FileHeader(1, 4), JobLevelUpTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJobMasterCtrl, new FileHeader(256, 4), JobMasterCtrlDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJobTutorialQuestList, new FileHeader("JTQ\0", 1, 2), JobTutorialQuestListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rKeyConfigTextTable, new FileHeader(1, 4), KeyConfigTextTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rLandInfo, new FileHeader("LAI\0", 4, 4), LandInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rLayout, new FileHeader("lot\0", 138, 4), LayoutDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rLayoutPreset, new FileHeader(5, 4), LayoutPresetDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rLocationData, new FileHeader("lcd\0", 16, 4), LocationDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMagicChantParam, new FileHeader(17, 4), MagicChantParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMagicCommandList, new FileHeader(27, 4), MagicCommandListTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMagicCommandWord, new FileHeader(1, 4), MagicCommandWordTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMapSpotData, new FileHeader("msd\0", 0, 4), MapSpotDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMapSpotStageList, new FileHeader("msl\0", 0, 4), MapSpotStageListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMsgSet, new FileHeader("mgst", 3, 2), MsgSetDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMyRoomActParam, new FileHeader(15, 4), MyRoomActParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNamedParam, new FileHeader(5, 4), NamedParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNormalSkillData, new FileHeader(5, 4), NormalSkillDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNpcConstItem, new FileHeader(2, 4), NpcConstItemDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNpcCustomSkill, new FileHeader(5, 4), NpcCustomSkillListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNpcIsNoSetPS3, new FileHeader(1, 4), NpcIsNoSetPS3TblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNpcIsUseJobParamEx, new FileHeader(1, 4), NpcIsUseJobParamExDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNpcLedgerList, new FileHeader("nll\0", 6, 4), NpcLedgerListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rNpcMeetingPlace, new FileHeader(0, 4), NpcMeetingPlaceDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOcdStatusParamRes, new FileHeader(37, 4), OcdStatusParamResListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOmParamPart, new FileHeader("OMPP", 69, 4), OmParamPartDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPartnerPawnTalk, new FileHeader("ppt\0", 1, 4), PartnerPawnTalkDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPartnerReactParam, new FileHeader(4, 4), PartnerReactParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPawnQuestTalk, new FileHeader("PQT\0", 1, 4), PawnQuestTalkDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPlPartsInfo, new FileHeader("PSI\0", 1, 4), PlPartsInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPrologueHmStatus, new FileHeader(0, 4), PrologueHmStatusDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPushRate, new FileHeader(256, 4), PushRateListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rQuestHistoryData, new FileHeader(1, 4), QuestHistoryDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rQuestMarkerInfo, new FileHeader("QMI\0", 1, 4), QuestMarkerInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rQuestSequenceList, new FileHeader(256, 4), QuestSequenceListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rQuestTextData, new FileHeader("QTD\0", 2, 4), QuestTextDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rRageTable, new FileHeader(257, 4), RageTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rReplaceWardGmdList, new FileHeader(1, 4), ReplaceWardGmdListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rRoomWearParam, new FileHeader(2, 4), RoomWearParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rShopGoods, new FileHeader("TBL\0", 259, 4), ShopGoodsDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rShotReqInfo, new FileHeader(9, 4), ShotReqInfoTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rShotReqInfo2, new FileHeader(9, 4), ShotReqInfo2TblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rShrinkBlowValue, new FileHeader(2, 4), ShrinkBlowValueDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rSituationMsgCtrl, new FileHeader("SMC\0", 3, 4), SituationMsgCtrlDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageAdjoinList, new FileHeader("SAL\0", 4, 4), StageAdjoinListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageAdjoinList2, new FileHeader("SAL2", 1, 4), StageAdjoinList2Deserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageConnect, new FileHeader("scc\0", 7, 4), StageConnectDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageCustom, new FileHeader("sca\0", 9, 4), StageCustomDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageCustomPartsEx, new FileHeader("scpx", 5, 4), StageCustomPartsExDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageInfo, new FileHeader("sti\0", 265, 4), StageInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageJoint, new FileHeader("sja\0", 19, 4), StageJointDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageList, new FileHeader("slt\0", 34, 4), StageListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageMap, new FileHeader(1, 4), StageMapDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageToSpot, new FileHeader(0, 4), StageToSpotDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStaminaDecTbl, new FileHeader("sdt\0", 7, 4), StaminaDecTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStartPosArea, new FileHeader(0, 4), StartPosAreaDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStatusCheck, new FileHeader(4, 4), StatusCheckTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStatusGainTable, new FileHeader(257, 4), StatusGainTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rTbl2ChatMacro, new FileHeader(256, 4), Tbl2ChatMacroDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rTexDetailEdit, new FileHeader("XFS\0", 393231, 4), TexDetailEditDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStartPos, new FileHeader("XFS\0", 196623, 4), StartPosDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOmKey, new FileHeader("XFS\0", 15, 4), OmKeyDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rTutorialDialogMessage, new FileHeader("TDM\0", 2, 4), TutorialDialogMessageDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rTutorialList, new FileHeader("TLT\0", 6, 4), TutorialListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rTutorialQuestGroup, new FileHeader("TQG\0", 1, 2), TutorialQuestGroupDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rVfxLightInfluence, new FileHeader(3, 4), VfxLightInfluenceListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWarpLocation, new FileHeader(353, 4), WarpLocationDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWaypoint, new FileHeader("WPT\0", 2, 4), WaypointDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWaypoint2, new FileHeader("WP2\0", 1, 4), WaypointDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWeaponOffset, new FileHeader(3, 4), WeaponOffsetTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWeaponResTable, new FileHeader(11, 4), WeaponResTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWeatherStageInfo, new FileHeader("WSI_", 7, 4), WeatherStageInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWepCateResTbl, new FileHeader(1, 4), WepCateResTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rQuestList, new FileHeader("XFS\0", 9043983, 4), QuestListDeserializer.class));


        clientResourceFileSet.add(new ClientResourceFile(rAbilityList, new FileHeader("abl0", 8, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.base.AbilityListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIPawnEmParam, new FileHeader(15, 4), AIPawnEmParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaMasterSpotData, new FileHeader(7, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.ui.uGUIAreaMaster.AreaMasterSpotDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAreaMasterSpotDetailData, new FileHeader(4, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.ui.uGUIAreaMaster.AreaMasterSpotDetailDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCatchInfoParam, new FileHeader(18, 4), CatchInfoParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCaughtInfoParam, new FileHeader(15, 4), CaughtInfoParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCharParamEnemy, new FileHeader("cpe\0", 10, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.EM.CharParamEnemyTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCustomSkillData, new FileHeader(1, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.skill.CustomSkillDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEmBaseInfoSv, new FileHeader(8, 4), EmBaseInfoSvDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rEventParam, new FileHeader(18, 4), EventParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rFurnitureData, new FileHeader(4, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.clankyoten.FurnitureDataDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rItemList, new FileHeader("ipa\0", 58, 4), ItemListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rLandInfo, new FileHeader("LAI\0", 2, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.base.LandInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rLayout, new FileHeader("lot\0", 117, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.stage.LayoutDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rMyRoomActParam, new FileHeader(14, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.MyRoom.MyRoomActParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOcdStatusParamRes, new FileHeader(23, 4), OcdStatusParamResListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOmParam, new FileHeader("TBL\0", 56, 4), OmParamDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rPlayerExpTable, new FileHeader(2, 4), PlayerExpTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rRoomWearParam, new FileHeader(1, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.MyRoom.RoomWearParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rSituationMsgCtrl, new FileHeader("SMC\0", 2, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.npc.SituationMsgCtrlDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageAdjoinList, new FileHeader("SAL\0", 3, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.marker.StageAdjoinListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageConnect, new FileHeader("scc\0", 1, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.stage.StageConnectDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageCustomParts, new FileHeader("scp\0", 17, 4), StageCustomPartsDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageInfo, new FileHeader("sti\0", 81, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.stage.StageInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStaminaDecTbl, new FileHeader("sdt\0", 5, 4), StaminaDecTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rTutorialList, new FileHeader("TLT\0", 5, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.tutorial_guide.TutorialListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWarpLocation, new FileHeader(352, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.gui_cmn.WarpLocationDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rWeaponResTable, new FileHeader(9, 4), WeaponResTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rOcdImmuneParamRes, new FileHeader(23, 4), OcdImmuneParamResTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rJumpParamTbl, new FileHeader(3, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.job.JumpParamTblDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStartPos, new FileHeader("XFS\0", 131087, 4), StartPosDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rQuestList, new FileHeader("XFS\0", 7667727, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season2.quest.QuestListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rAIFSM, new FileHeader("XFS\0", 131087, 4), AIFSMDeserializer.class));


        clientResourceFileSet.add(new ClientResourceFile(rAreaInfo, new FileHeader("ARI\0", 1, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season1.game_common.AreaInfoDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageAdjoinList, new FileHeader("SAL\0", 2, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season1.marker.StageAdjoinListDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rStageCustomParts, new FileHeader("scp\0", 16, 4), org.sehkah.ddon.tools.extractor.season1.logic.resource.deserialization.season1.stage.StageCustomPartsDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftWepQualityParam, new FileHeader(2, 4), CraftWepQualityParamTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftArmQualityParam, new FileHeader(3, 4), CraftArmQualityParamTableDeserializer.class));

        clientResourceFileSet.add(new ClientResourceFile(rCraftRecipe, new FileHeader("RCP\0", 6, 4), CraftRecipeDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftSkillGain, new FileHeader(2, 4), CraftSkillGainTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftSkillStr, new FileHeader(4, 4), CraftSkillStrTableDeserializer.class));
        clientResourceFileSet.add(new ClientResourceFile(rCraftSkillBurst, new FileHeader(2, 4), CraftSkillBurstTableDeserializer.class));
    }
}
