package org.sehkah.ddon.tools.extractor.season3.logic.resource.entity.base.meta;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

public enum ItemListElementParamKind {
    KIND_NONE_ELEMENT(0x0),
    WEIGHT_DOWN_ELEMENT(0x1),
    SpredSav_UP_ELEMENT(0x2),
    FreezeSav_UP_ELEMENT(0x3),
    ShockSav_UP_ELEMENT(0x4),
    CrossSav_UP_ELEMENT(0x5),
    BlindSav_UP_ELEMENT(0x6),
    ATTACK_UP_ELEMENT(0x7),
    MAGICATTACK_UP_ELEMENT(0x8),
    POWERREV_UP_ELEMENT(0x9),
    StanSav_UP_ELEMENT(0xA),
    PoisonSav_UP_ELEMENT(0xB),
    SlowSav_UP_ELEMENT(0xC),
    SleepSav_UP_ELEMENT(0xD),
    WaterSav_UP_ELEMENT(0xE),
    OilSav_UP_ELEMENT(0xF),
    SealSav_UP_ELEMENT(0x10),
    SoftBodySav_UP_ELEMENT(0x11),
    StoneSav_UP_ELEMENT(0x12),
    GoldSav_UP_ELEMENT(0x13),
    FallFireSav_UP_ELEMENT(0x14),
    FallIceSav_UP_ELEMENT(0x15),
    FallThunderSav_UP_ELEMENT(0x16),
    FallSaintSav_UP_ELEMENT(0x17),
    FallBlindSav_UP_ELEMENT(0x18),
    FallAttackSav_UP_ELEMENT(0x19),
    FallDefSav_UP_ELEMENT(0x1A),
    FallMagicSav_UP_ELEMENT(0x1B),
    FallMagicDefSav_UP_ELEMENT(0x1C),
    DEFENCE_UP_ELEMENT(0x1D),
    MAGICDEFENSE_UP_ELEMENT(0x1E),
    DURABILITY_UP_ELEMENT(0x1F),
    SPIRIT_UP_ELEMENT(0x20),
    HP_UP_ELEMENT(0x21),
    ST_UP_ELEMENT(0x22),
    ShinRyokuRev_UP_ELEMENT(0x23),
    FireEleDef_UP_ELEMENT(0x24),
    IceEleDef_UP_ELEMENT(0x25),
    ThunderEleDef_UP_ELEMENT(0x26),
    SaintEleDef_UP_ELEMENT(0x27),
    DarkEleDef_UP_ELEMENT(0x28),
    SpredDef_UP_ELEMENT(0x29),
    FreezeDef_UP_ELEMENT(0x2A),
    ShockDef_UP_ELEMENT(0x2B),
    CrossDef_UP_ELEMENT(0x2C),
    BlindDef_UP_ELEMENT(0x2D),
    PoisonDef_UP_ELEMENT(0x2E),
    SlowDef_UP_ELEMENT(0x2F),
    SleepDef_UP_ELEMENT(0x30),
    StanDef_UP_ELEMENT(0x31),
    WaterDef_UP_ELEMENT(0x32),
    OilDef_UP_ELEMENT(0x33),
    SealDef_UP_ELEMENT(0x34),
    CurseDef_UP_ELEMENT(0x35),
    SoftBodyDef_UP_ELEMENT(0x36),
    StoneDef_UP_ELEMENT(0x37),
    GoldDef_UP_ELEMENT(0x38),
    FallFireDef_UP_ELEMENT(0x39),
    FallIceDef_UP_ELEMENT(0x3A),
    FallThunderDef_UP_ELEMENT(0x3B),
    FallSaintDef_UP_ELEMENT(0x3C),
    FallBlindDef_UP_ELEMENT(0x3D),
    FallAttackDef_UP_ELEMENT(0x3E),
    FallDefenceDef_UP_ELEMENT(0x3F),
    FallMagicAttackDef_UP_ELEMENT(0x40),
    FallMagicDefenceDef_UP_ELEMENT(0x41),
    VsEm00_UP_ELEMENT(0x42),
    VsEm01_UP_ELEMENT(0x43),
    VsEm02_UP_ELEMENT(0x44),
    VsEm03_UP_ELEMENT(0x45),
    VsEm04_UP_ELEMENT(0x46),
    VsEm05_UP_ELEMENT(0x47),
    VsEm06_UP_ELEMENT(0x48),
    VsEm07_UP_ELEMENT(0x49),
    VsEm08_UP_ELEMENT(0x4A),
    VsEm09_UP_ELEMENT(0x4B),
    VsEm10_UP_ELEMENT(0x4C),
    VsEm11_UP_ELEMENT(0x4D),
    VsEm12_UP_ELEMENT(0x4E),
    VsEm13_UP_ELEMENT(0x4F),
    VsEm14_UP_ELEMENT(0x50),
    Color_ELEMENT(0x51),
    DASH_ST_UP(0x52),
    JUMP_UP(0x53),
    CLIME_SPD_UP(0x54),
    AWAKENING_WEIGHT_LIGHTRY(0x55),
    LOW_LV_EXP_UP(0x56),
    ABILITY(0x57),
    VsEm15_UP_ELEMENT(0x58),
    ELEMENT_PARAM_KIND_UNKNOWN(Integer.MAX_VALUE);

    private static final Map<Short, ItemListElementParamKind> ordinalMap = Arrays.stream(values()).collect(Collectors.toMap(e -> (short) e.value, Function.identity()));
    public final long value;

    ItemListElementParamKind(long value) {
        this.value = value;
    }

    public static ItemListElementParamKind of(Short n) {
        return ordinalMap.getOrDefault(n, ELEMENT_PARAM_KIND_UNKNOWN);
    }
}
