name: CD - Windows JPackage

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read

jobs:
  windows-jpackage:
    runs-on: windows-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          check-latest: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
          cache-cleanup: on-success
          cache-read-only: false

      - name: Assemble CLI
        run: ./gradlew :cli:assemble --no-daemon --info

      - name: Build Windows JPackage
        run: ./gradlew :cli:jpackage --no-daemon --info

      - name: Upload Windows JPackage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: distribution-jpackage-windows
          path: cli/build/jpackage/
          retention-days: 7
          if-no-files-found: error
