name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
    tags: [ "v*" ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.adoc'
      - 'output/**'
      - '*.log'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.adoc'
      - 'output/**'
      - '*.log'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# Use bash uniformly across runners to make ./gradlew consistent
defaults:
  run:
    shell: bash

env:
  JAVA_VERSION: '25'

jobs:
  linux-build-test-dist:
    name: Linux • Build, Test, Dist
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        check-latest: true

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        gradle-home-cache-cleanup: true
        dependency-graph: generate-and-submit

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Check dependency updates
      run: ./gradlew dependencyUpdates -Drevision=release

    - name: Upload dependency report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-updates-report
        path: build/dependencyUpdates/
        retention-days: 1
        compression-level: 1
        if-no-files-found: ignore

    - name: Assemble (no tests)
      run: ./gradlew assemble

    - name: Run tests
      run: ./gradlew test

    - name: Generate test report (Linux)
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results (ubuntu-latest, Java ${{ env.JAVA_VERSION }})
        path: '**/build/test-results/test/TEST-*.xml'
        reporter: java-junit
        fail-on-error: false

    - name: Upload test results (Linux)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-ubuntu-latest-java${{ env.JAVA_VERSION }}
        path: |
          **/build/test-results/
          **/build/reports/tests/
        retention-days: 1
        compression-level: 1
        if-no-files-found: ignore

    - name: Build JLink distribution (Linux)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: ./gradlew :cli:jlink

    - name: Upload distribution artifacts (Linux)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: distribution-ubuntu-latest
        path: |
          cli/build/image/
        retention-days: 1
        compression-level: 1
        if-no-files-found: ignore

  windows-build-test-dist:
    name: Windows • Build, Test, Dist
    runs-on: windows-latest
    needs: linux-build-test-dist
    timeout-minutes: 45
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        check-latest: true

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.event_name == 'pull_request' }}
        gradle-home-cache-cleanup: true

    - name: Assemble (no tests)
      run: ./gradlew assemble

    - name: Run tests
      run: ./gradlew test

    - name: Generate test report (Windows)
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results (windows-latest, Java ${{ env.JAVA_VERSION }})
        path: '**/build/test-results/test/TEST-*.xml'
        reporter: java-junit
        fail-on-error: false

    - name: Upload test results (Windows)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-windows-latest-java${{ env.JAVA_VERSION }}
        path: |
          **/build/test-results/
          **/build/reports/tests/
        retention-days: 1
        compression-level: 1
        if-no-files-found: ignore

    - name: Build JLink distribution (Windows)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: ./gradlew :cli:jlink

    - name: Build JPackage (Windows)
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: ./gradlew :cli:jpackage

    - name: Upload distribution artifacts (Windows)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: distribution-windows-latest
        path: |
          cli/build/jpackage/
        retention-days: 1
        compression-level: 1
        if-no-files-found: ignore
